config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,  :controllers => { :registrations => "users/registrations" }

  resources :users do
    resources :tasks
  end

  resources :farms do
    resources :employees, only: [:index]
    resources :lotes
    resources :sub_lotes
  end

  root "static_pages#home"

end

app/models/lote.rb
class Lote < ActiveRecord::Base
  belongs_to :farm
  has_many :sub_lotes
  validates :name, presence: true
  validates :size, presence: true
  validates :fruit_type, presence: true


  def tree_count
    self.sub_lotes.sum(:tree_count)
  end

end

app/controllers/lotes_controller.rb
class LotesController < ApplicationController
  # skip_authorize_resource :only => :new
  load_and_authorize_resource :only => [:show,:destroy,:edit,:update, :new]

  def index
    @farm = Farm.find(params[:farm_id])
    @lotes = @farm.lotes
  end

  def show
  end

  def new
    @lote = Lote.new
  end

  def create
    @lote = Lote.new(lote_params)
    if @lote.save
      flash[:success]  = "Nuevo lote creado Exitosamente"
      redirect_to farm_lotes_path(@lote.farm)
    else
      flash.now[:danger] = "No fue posible crear lote"
      render :new
    end
  end

  def edit
  end

  def update
    @lote = Lote.find(params[:id])
    if @lote.update(lote_params)
      flash[:success] = "Lote Exitosamente Editado"
      redirect_to farm_lote_path(@lote.farm, @lote)
    else
      render :edit
    end
  end

  def destroy
    @lote.destroy!
    flash[:success] = "Lote Destruido"
    redirect_to farm_lotes_path(@lote.farm)
  end

  private

  def lote_params
    params.require(:lote).permit(:name, :size, :fruit_type, :farm_id)
  end


end

app/helpers/lotes_helper.rb
module LotesHelper
end

app/views/lotes/edit.html.erb
<%= simple_form_for(@lote, url: farm_lote_path(params[:farm_id], @lote),html:{class: "form-signin"}, method: :patch) do |f| %>
  <%= f.error_notification %>

  <h2>Editar Lote <%= @lote.name %></h2>

  <div class="form-inputs">
    <%= f.input :name, required: true %>
    <%= f.input :size, required: true %>
    <%= f.input :fruit_type, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Editar" %>
  </div>
  <%= link_to "Atras", :back %>

<% end %>

app/views/lotes/index.html.erb
<div class="row">
  <h2 class="text-center">Lotes <%= @farm.name %></h2>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Cantidad de Lotes</h3>
      </div>
      <div class="panel-body">
        <%= @lotes.count %>
      </div>
    </div>
    <% if can?(:create, Lote) %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Acciones</h3>
        </div>
        <div class="panel-body">
          <div class="list-group">
            <%= link_to "Crear nuevo Lote", new_farm_lote_path(@farm), class: "list-group-item" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Lotes</h3>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Tamaño</th>
            <th>Fruta</th>
          </tr>
        </thead>
        <tbody>
          <% @lotes.each do |lote| %>
            <tr>
              <td><%= link_to lote.name, farm_lote_path(@farm, lote) %></td>
              <td><%= lote.size %></td>
              <td><%= lote.fruit_type %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-8 pull-right">
    <%= pie_chart @lotes.group(:fruit_type).count %>
  </div>
</div>

<%= link_to "Atras", :back %>

app/views/lotes/new.html.erb
<%= simple_form_for(@lote, url: farm_lotes_path(params[:farm_id]),html:{class: "form-signin"}) do |f| %>
  <%= f.error_notification %>

  <h2>Nuevo Lote</h2>

  <div class="form-inputs">
    <%= f.input :name, required: true %>
    <%= f.input :size, required: true %>
    <%= f.input :fruit_type, required: true %>
    <%= f.hidden_field :farm_id, value: params[:farm_id] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Crear nuevo Lote" %>
  </div>
  <%= link_to "Atras", :back %>

<% end %>

app/views/lotes/show.html.erb
<div class="row">
  <h2 class="text-center">Lote <%= @lote.name %></h2>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Caracteristicas</h3>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>Fruta</th>
            <th>Tamaño(Ha)</th>
            <th>Sub-Lotes</th>
            <th>Numero de Arboles</th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td class="text-center"><%= @lote.fruit_type%></td>
              <td class="text-center"><%= @lote.size %></td>
              <td class="text-center"><%= @lote.sub_lotes.count %></td>
              <td class="text-center"><%= @lote.tree_count %></td>
            </tr>
        </tbody>
      </table>
    </div>
    <% if can?(:manage, Lote) %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Acciones</h3>
        </div>
        <div class="panel-body">
          <div class="list-group">
            <%= link_to "Editar Lote", edit_farm_lote_path(@lote.farm, @lote), class: "list-group-item" %>
            <%= link_to "Destruir Lote", farm_lote_path(@lote.farm, @lote), class: "list-group-item", method: :delete, data: {confirm:"Esta seguro de destruir lote"} %>
            <%= link_to "Crear Sub Lote", new_farm_sub_lote_path(@lote.farm, lote_id: @lote.id), class: "list-group-item" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-8  ">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Sub-Lotes</h3>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Codigo</th>
            <th>Arboles</th>
            <th>Edad</th>
            <th>Variedad</th>
          </tr>
        </thead>
        <tbody>
          <% @lote.sub_lotes.each do |sub_lote| %>
            <tr>
              <td><%= link_to sub_lote.name, farm_sub_lote_path(@lote.farm, sub_lote) %></td>
              <td><%= sub_lote.code %></td>
              <td><%= sub_lote.tree_count %></td>
              <td><%= time_ago_in_words(sub_lote.plantation_date) %></td>
              <td><%= sub_lote.fruit_variety %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= pie_chart @lote.sub_lotes.group(:fruit_variety).sum(:tree_count) %>
  </div>
</div>
<%= link_to "Atras", :back %>