config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,  :controllers => { :registrations => "users/registrations" }

  resources :users do
    resources :tasks
  end

  resources :farms do
    resources :employees, only: [:index]
    resources :lotes
    resources :sub_lotes
  end

  root "static_pages#home"

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = User.where(farm_id: params[:farm_id])
    @farm = Farm.find(params[:farm_id])
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/index.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Administradores</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @employees.each do |employee| %>
            <% if employee.role?(:farm_admin)%>
              <li><%= link_to employee.name, user_path(employee) %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Directos</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @employees.each do |employee| %>
            <% if employee.role?(:employee) %>
              <li><%= link_to employee.name, user_path(employee) %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Contratistas</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @employees.each do |employee| %>
            <% if employee.role?(:subcontract)  %>
              <li><%= link_to employee.name, user_path(employee) %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
 </div>
</div>
<div class="row">
  <div class="col-md-3">
    <% if can?(:create, User) %>
      <%= link_to "Crear Empleado", new_user_path(farm_id: @farm) %>
    <% end %>
  </div>
</div>
<%= link_to "Atras", :back %>