config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,  :controllers => { :registrations => "users/registrations" }

  resources :users do
    resources :tasks
  end

  resources :farms do
    resources :employees, only: [:index]
    resources :lotes
    resources :sub_lotes
  end

  root "static_pages#home"

end

app/models/sub_lote.rb
class SubLote < ActiveRecord::Base
  belongs_to :lote
  belongs_to :farm
  has_many :production_reports
  validates :name, presence: true
  validates :fruit_variety, presence: true
  validates :plantation_date, presence: true
  validates :code, presence: true
  validates :tree_count, presence: true

  def last_month_production_amount
    self.production_reports.where('created_at BETWEEN ? AND ?', DateTime.now.in_time_zone.beginning_of_month, DateTime.now.in_time_zone.end_of_month).sum(:amount)
  end

end

app/controllers/sub_lotes_controller.rb
class SubLotesController < ApplicationController
  load_and_authorize_resource :only => [:show,:destroy,:edit,:update]


  def index
    @farm = Farm.find(params[:farm_id])
    @sub_lotes = @farm.sub_lotes
  end

  def show
    @time_frame = params[:time_frame]
  end

  def new
    @sub_lote = SubLote.new
  end

  def create
    @sub_lote = SubLote.new(sub_lote_params)
    if @sub_lote.save
      flash[:success] = "Nuevo Sub-Lote creado exitosamente"
      redirect_to farm_lote_path(@sub_lote.lote.farm, @sub_lote.lote)
    else
      flash[:danger] = "Error al crear Sub-Lote"
      @lote_id = @sub_lote.lote.id
      render :new
    end
  end

  def edit
  end

  def update
    @sub_lote = SubLote.find(params[:id])
    if @sub_lote.update(sub_lote_params)
      flash[:success] = "Sub-Lote Exitosamente Editado"
      redirect_to farm_sub_lote_path(@sub_lote.lote.farm, @sub_lote)
    else
      render :edit
    end
  end

  def destroy
    @sub_lote.destroy!
    flash[:success] = "Sub-Lote Destruido"
    redirect_to farm_lote_path(@sub_lote.lote.farm, @sub_lote.lote)
  end

  private

  def sub_lote_params
    params.require(:sub_lote).permit(:name, :code, :tree_count, :plantation_date, :fruit_variety, :lote_id)
  end
end

app/helpers/sub_lotes_helper.rb
module SubLotesHelper
end

app/views/sub_lotes/edit.html.erb
<%= simple_form_for(@sub_lote, url: farm_sub_lote_path(params[:farm_id], @sub_lote), html: {class: "form-signin"}, method: :patch) do |f| %>
  <%= f.error_notification %>

  <h2>Editar <%= @sub_lote.name %></h2>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :code %>
    <%= f.input :tree_count %>
    <%= f.input :fruit_variety %>
    <%= f.input :plantation_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Editar Sub-Lote" %>
  </div>
  <%= link_to "Atras", :back %>

<% end %>

app/views/sub_lotes/index.html.erb
<div class="row">
  <h2 class="text-center">Sub-lotes de <%= @farm.name  %></h2>
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Sub-Lotes</h3>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Codigo</th>
            <th>Arboles</th>
            <th>Edad</th>
            <th>Variedad</th>
          </tr>
        </thead>
        <tbody>
          <% @sub_lotes.each do |sub_lote| %>
            <tr>
              <td><%= link_to sub_lote.name, farm_sub_lote_path(params[:farm_id], sub_lote) %></td>
              <td><%= sub_lote.code %></td>
              <td><%= sub_lote.tree_count %></td>
              <td><%= time_ago_in_words(sub_lote.plantation_date) %></td>
              <td><%= sub_lote.fruit_variety %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/sub_lotes/new.html.erb
<%= simple_form_for(@sub_lote, url: farm_sub_lotes_path(params[:farm_id]),html:{class: "form-signin"}) do |f| %>
  <%= f.error_notification %>

  <h2>Nuevo Sub-Lote</h2>

  <div class="form-inputs">
    <%= f.input :name, required: true %>
    <%= f.input :code, required: true %>
    <%= f.input :tree_count, required: true %>
    <%= f.input :fruit_variety, required: true %>
    <%= f.input :plantation_date, required: true %>
    <% if @lote_id %>
      <%= f.hidden_field :lote_id, value: @lote_id %>
    <% else %>
      <%= f.hidden_field :lote_id, value: params[:lote_id] %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Crear Sub-Lote" %>
  </div>
  <%= link_to "Atras", :back %>

<% end %>

app/views/sub_lotes/show.html.erb
<div class="row">
  <h2 class="text-center"><%= @sub_lote.name %></h2>
  <br>
  <div class="col-md-8 col-md-offset-4 ">
    <div class="btn-toolbar">
      <%= link_to "Semanas", farm_sub_lote_path(params[:farm_id], @sub_lote, time_frame: "week" ), class: "btn btn-default " %>
      <%= link_to "Meses", farm_sub_lote_path(params[:farm_id], @sub_lote), class: "btn btn-default" %>
      <%= link_to "Años", farm_sub_lote_path(params[:farm_id], @sub_lote, time_frame: "year" ), class: "btn btn-default" %>
    </div>
  </div>
</div>
<div class='row'>
  <br>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Resumen</h3>
      </div>
      <div class="panel-body">
        <div class="list-group">
          <li class="list-group-item"><strong>Produccion ultimo mes:</strong> <%= @sub_lote.last_month_production_amount %> Toneladas</li>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Acciones</h3>
      </div>
      <div class="panel-body">
        <div class="list-group">
          <%= link_to "Editar Sub-Lote", edit_farm_sub_lote_path(params[:farm_id], @sub_lote), class: "list-group-item" %>
          <%= link_to "Destruir Sub-Lote", farm_sub_lote_path(params[:farm_id], @sub_lote), class: "list-group-item", method: :delete, data: {confirm:"Esta seguro de destruir lote"} %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-8 ">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Curva de Produccion</h3>
      </div>
      <div class="panel-body">
        <% if @time_frame == "week"  %>
          <%= line_chart @sub_lote.production_reports.group_by_week(:created_at).sum(:amount), class: "pull-left" %>
        <% elsif @time_frame == "year" %>
          <%= line_chart @sub_lote.production_reports.group_by_year(:created_at).sum(:amount) %>
        <% else %>
          <%= line_chart @sub_lote.production_reports.group_by_month(:created_at).sum(:amount) %>
        <% end %>
      </div>
    </div>
  </div>
</div>